# Generated by Django 6.0.7 on 2026-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment', max_length=200)),
                ('category', models.CharField(help_text='Category like Laptop, Camera, etc.', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the equipment')),
                ('daily_price', models.DecimalField(decimal_places=2, help_text='Rental price per day', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items available')),
                ('available', models.BooleanField(default=True, help_text='Is this equipment currently available for rent?')),
                ('image', models.ImageField(blank=True, help_text='Photo of the equipment', null=True, upload_to='equipment_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when this equipment was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated date')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
    ]
