# Generated by Django 6.0.7 on 2026-07-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the request was made')),
                ('start_date', models.DateField(help_text='Date when the rental should start')),
                ('end_date', models.DateField(help_text='Date when the rental should end')),
                ('returned_at', models.DateField(blank=True, help_text='Date when the equipment was actually returned', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', help_text='Current status of the rental request', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the rental request', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (reasons for rejection, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the rental request', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipment being requested', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Rental Request',
                'verbose_name_plural': 'Rental Requests',
                'ordering': ['-request_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('customer', 'equipment'), name='unique_active_rental_request')],
            },
        ),
    ]
